[workspace]
members = [
  "programs/market-registry",
  "programs/escrow-vault",
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
[programs.localnet]
market_registry = "2bRruB58Pk39PRz2wpAhSjURJMKpWoZdpiozzRLruqyU"
escrow_vault = "7naTChgbgNS8cUoMbfKoYA8qomHJVUf5oeVjv9iSmiyf"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn ts-mocha -p tsconfig.json -t 1000000 tests/**/*.test.ts"
