[workspace]
members = [
  "programs/market-registry",
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
[programs.localnet]
market_registry = "2bRruB58Pk39PRz2wpAhSjURJMKpWoZdpiozzRLruqyU"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn ts-mocha -p tsconfig.json -t 1000000 tests/**/*.test.ts"
